FROM odoo:16

COPY --chown=odoo:odoo ./modules /mnt/extra-addons


COPY --chown=odoo:odoo ./submodules/account-payment/account_cashbox /mnt/extra-addons/account_cashbox
COPY --chown=odoo:odoo ./submodules/account-payment/account_cashbox_l10n_latam_check /mnt/extra-addons/account_cashbox_l10n_latam_check
COPY --chown=odoo:odoo ./submodules/account-payment/account_payment_group /mnt/extra-addons/account_payment_group
COPY --chown=odoo:odoo ./submodules/account-payment/account_payment_group_financial_surcharge /mnt/extra-addons/account_payment_group_financial_surcharge
COPY --chown=odoo:odoo ./submodules/account-payment/account_payment_invoice /mnt/extra-addons/account_payment_invoice
COPY --chown=odoo:odoo ./submodules/account-payment/account_payment_multi /mnt/extra-addons/account_payment_multi
COPY --chown=odoo:odoo ./submodules/account-payment/account_payment_ux /mnt/extra-addons/account_payment_ux
COPY --chown=odoo:odoo ./submodules/account-payment/account_withholding /mnt/extra-addons/account_withholding
COPY --chown=odoo:odoo ./submodules/account-payment/account_withholding_automatic /mnt/extra-addons/account_withholding_automatic
COPY --chown=odoo:odoo ./submodules/account-payment/card_installment /mnt/extra-addons/card_installment

COPY --chown=odoo:odoo ./submodules/account-financial-tools/account_debt_report /mnt/extra-addons/account_debt_report
COPY --chown=odoo:odoo ./submodules/account-financial-tools/account_financial_amount /mnt/extra-addons/account_financial_amount
COPY --chown=odoo:odoo ./submodules/account-financial-tools/account_interests /mnt/extra-addons/account_interests
COPY --chown=odoo:odoo ./submodules/account-financial-tools/account_journal_security /mnt/extra-addons/account_journal_security
COPY --chown=odoo:odoo ./submodules/account-financial-tools/account_payment_term_surcharge /mnt/extra-addons/account_payment_term_surcharge
COPY --chown=odoo:odoo ./submodules/account-financial-tools/account_ux /mnt/extra-addons/account_ux

COPY --chown=odoo:odoo ./submodules/odoo-argentina/account_check /mnt/extra-addons/account_check
COPY --chown=odoo:odoo ./submodules/odoo-argentina/account_debt_management /mnt/extra-addons/account_debt_management
COPY --chown=odoo:odoo ./submodules/odoo-argentina/account_financial_amount /mnt/extra-addons/account_financial_amount
COPY --chown=odoo:odoo ./submodules/odoo-argentina/account_move_tax /mnt/extra-addons/account_move_tax
COPY --chown=odoo:odoo ./submodules/odoo-argentina/account_payment_fix /mnt/extra-addons/account_payment_fix
COPY --chown=odoo:odoo ./submodules/odoo-argentina/account_payment_group /mnt/extra-addons/account_payment_group
COPY --chown=odoo:odoo ./submodules/odoo-argentina/account_withholding /mnt/extra-addons/account_withholding
COPY --chown=odoo:odoo ./submodules/odoo-argentina/account_withholding_automatic /mnt/extra-addons/account_withholding_automatic
COPY --chown=odoo:odoo ./submodules/odoo-argentina/currencies /mnt/extra-addons/currencies
COPY --chown=odoo:odoo ./submodules/odoo-argentina/l10n_ar_account_agipinfo /mnt/extra-addons/l10n_ar_account_agipinfo
COPY --chown=odoo:odoo ./submodules/odoo-argentina/l10n_ar_account_iva_digital /mnt/extra-addons/l10n_ar_account_iva_digital
COPY --chown=odoo:odoo ./submodules/odoo-argentina/l10n_ar_account_vat_ledger /mnt/extra-addons/l10n_ar_account_vat_ledger
COPY --chown=odoo:odoo ./submodules/odoo-argentina/l10n_ar_account_withholding /mnt/extra-addons/l10n_ar_account_withholding
COPY --chown=odoo:odoo ./submodules/odoo-argentina/l10n_ar_afipws /mnt/extra-addons/l10n_ar_afipws
COPY --chown=odoo:odoo ./submodules/odoo-argentina/l10n_ar_afipws_fe /mnt/extra-addons/l10n_ar_afipws_fe
COPY --chown=odoo:odoo ./submodules/odoo-argentina/l10n_ar_bank /mnt/extra-addons/l10n_ar_bank
COPY --chown=odoo:odoo ./submodules/odoo-argentina/l10n_ar_export_sicore /mnt/extra-addons/l10n_ar_export_sicore
COPY --chown=odoo:odoo ./submodules/odoo-argentina/l10n_ar_fe_qr /mnt/extra-addons/l10n_ar_fe_qr
COPY --chown=odoo:odoo ./submodules/odoo-argentina/l10n_ar_invoices_view /mnt/extra-addons/l10n_ar_invoices_view
COPY --chown=odoo:odoo ./submodules/odoo-argentina/l10n_ar_padron /mnt/extra-addons/l10n_ar_padron
COPY --chown=odoo:odoo ./submodules/odoo-argentina/l10n_ar_partner /mnt/extra-addons/l10n_ar_partner
COPY --chown=odoo:odoo ./submodules/odoo-argentina/l10n_ar_percepciones /mnt/extra-addons/l10n_ar_percepciones
COPY --chown=odoo:odoo ./submodules/odoo-argentina/l10n_ar_point_of_sale /mnt/extra-addons/l10n_ar_point_of_sale
COPY --chown=odoo:odoo ./submodules/odoo-argentina/l10n_ar_purchase_taxes /mnt/extra-addons/l10n_ar_purchase_taxes
COPY --chown=odoo:odoo ./submodules/odoo-argentina/l10n_ar_report_payment_group /mnt/extra-addons/l10n_ar_report_payment_group
COPY --chown=odoo:odoo ./submodules/odoo-argentina/l10n_ar_report_stock /mnt/extra-addons/l10n_ar_report_stock
COPY --chown=odoo:odoo ./submodules/odoo-argentina/l10n_ar_report_withholding /mnt/extra-addons/l10n_ar_report_withholding
COPY --chown=odoo:odoo ./submodules/odoo-argentina/l10n_ar_rg5003 /mnt/extra-addons/l10n_ar_rg5003
COPY --chown=odoo:odoo ./submodules/odoo-argentina/l10n_ar_stock /mnt/extra-addons/l10n_ar_stock

COPY --chown=odoo:odoo ./submodules/odoo_chasqui_integration /mnt/extra-addons/odoo4chasqui
COPY --chown=odoo:odoo ./submodules/odoo4chasqui


COPY --chown=odoo:odoo transport.py /var/lib/odoo/.local/lib/python3.9/site-packages/pysimplesoap/transport.py

USER root
RUN apt-get update && apt-get install git -y
RUN apt-get install python3-xlrd python3-chardet python3-ofxparse -y
COPY openssl.cnf /etc/ssl/openssl.cnf

USER odoo
RUN pip3 install future
RUN pip3 install pyOpenSSL
RUN pip3 install pysimplesoap

RUN python3 -m pip install "httplib2==0.20.4"
RUN python3 -m pip install "git+https://github.com/pysimplesoap/pysimplesoap@a330d9c4af1b007fe1436f979ff0b9f66613136e"
RUN python3 -m pip install "git+https://github.com/ingadhoc/pyafipws@py3k"
RUN python3 -m pip install "git+https://github.com/OCA/openupgradelib/@master"
