version: '3.1'
services:
  web:
    image: odoo-base:1.0
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
      replicas: 1    
      resources:
        limits:
          cpus: '2'
          memory: 2048M
        reservations:
          cpus: '1'
          memory: 1024M
    ports:
      - "8069:8069"
    environment:
      - HOST=172.28.45.254
      - USER=odoo_user
      - PASSWORD_FILE=/run/secrets/postgresql_password
    volumes:
      - odoo-web-data:/var/lib/odoo
    secrets:
      - postgresql_password

volumes:
  odoo-web-data:

secrets:
  postgresql_password:
    file: odoo_pg_pass
